interface JsonLdProps {
  /** Schema.org node or graph, already serialised by lib/structured-data. */
  data: unknown;
}

/**
 * Emits a JSON-LD block. This is a server component on purpose: structured data
 * belongs in the initial HTML for crawlers that do not execute JavaScript, and
 * marking it "use client" would ship a hydration bundle to render one script tag.
 */
export function JsonLd({ data }: JsonLdProps) {
  return (
    <script
      type="application/ld+json"
      // Schema payloads are generated by us from typed calendar data, never
      // from user input, so there is nothing to escape here.
      dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }}
    />
  );
}
